"""Public package exports for PACT."""

from importlib import import_module
from typing import TYPE_CHECKING

from pact.metadata import PACKAGE_VERSION

if TYPE_CHECKING:
    from pact.canonical import (
        CanonicalizationProfile,
        ContentCanonicalizationError,
        canonical_json,
        canonicalize_content,
    )
    from pact.carriers import (
        PACT_XML_NAMESPACE,
        C2paAsset,
        C2paError,
        C2paReadResult,
        C2paSignerMaterial,
        CarrierError,
        CarrierMode,
        ExternalManifestReference,
        InvisibleLocator,
        StructuredCarrierExtraction,
        TextCarrierExtraction,
        build_c2pa_manifest_definition,
        build_external_manifest_reference,
        c2pa_pdf_embedding_supported,
        c2pa_supported_builder_mime_types,
        c2pa_supported_embedded_document_mime_types,
        c2pa_supported_embedded_image_mime_types,
        c2pa_supported_reader_mime_types,
        embed_c2pa_image,
        embed_c2pa_manifest_in_pdf,
        embed_c2pa_manifest_in_zip_document,
        embed_html_carrier,
        embed_text_carrier,
        embed_xml_carrier,
        extract_c2pa_manifest_from_pdf,
        extract_c2pa_manifest_from_zip_document,
        extract_html_carrier,
        extract_text_carrier,
        extract_xml_carrier,
        pdf_external_manifest_reference,
        read_c2pa_asset,
        sign_c2pa_document,
        sign_c2pa_manifest_store,
    )
    from pact.crypto import (
        CryptographyError,
        base64url_decode,
        base64url_encode,
    )
    from pact.detection import (
        ConfidenceInterval,
        EvidenceSignal,
        HypothesisTest,
        Probe,
        ProbeAnalysisReport,
        ProbeConclusion,
        ProbeEvidencePackage,
        ProbeEvidenceSignature,
        ProbeKind,
        ProbeMeasurement,
        ProbeResponse,
        ProbeSet,
        TrainingUseRiskLevel,
        TrainingUseRiskReport,
        analyze_probe_responses,
        create_probe_set,
        create_training_use_risk_report,
        responses_from_jsonl,
    )
    from pact.identity import (
        ClaimantIdentity,
        DeviceBindingError,
        DeviceIdentityBinding,
        EncryptedFileIdentityStore,
        IdentityError,
        IdentityNotFoundError,
        IdentityStorageError,
        KeyringIdentityStore,
        LocalDeviceBindingStore,
        normalize_registry_url,
    )
    from pact.inspection import inspect_content
    from pact.manifest import (
        C2PAAction,
        C2PAIngredient,
        ClaimMeaning,
        ContentBinding,
        Manifest,
        ManifestError,
        ManifestSignature,
        SignedManifest,
        VerificationReport,
        sign_manifest,
        verify_manifest,
    )
    from pact.policy import (
        Permission,
        PermissionValue,
        Policy,
        PolicyEntry,
        PolicyError,
    )
    from pact.privacy import (
        PrivacyAuditError,
        PrivacyAuditReport,
        PrivacyFinding,
        PrivacySeverity,
        audit_public_json_payload,
        audit_registry_claim_payload,
        audit_signed_manifest_publication,
    )
    from pact.registry import (
        ChallengePurpose,
        ClaimantProfile,
        ClaimVerificationReport,
        DisputeRecord,
        DisputeStatus,
        EvidenceProfile,
        FileRegistryStore,
        KeyRotationRequest,
        MutationChallenge,
        MutationRequest,
        PostgresRegistryStore,
        RegisteredClaim,
        RegistryBatch,
        RegistryCertificateAuthority,
        RegistryError,
        RegistryEvent,
        RegistryEventType,
        RegistryService,
        RegistryStore,
        RegistryStoreError,
        SqliteRegistryStore,
        TrustLabel,
        TrustTier,
        VerificationLabel,
        merkle_root,
    )
    from pact.server import (
        AuthProvider,
        AwsLambdaRoute,
        CognitoAuthorizerConfig,
        DeploymentMode,
        RouteAuth,
        RouteConfig,
        RuntimeConfig,
        SecurityProfile,
        StoreBackend,
        aws_lambda_routes,
        create_registry_store,
        default_routes,
    )
    from pact.watermarks import (
        PERCEPTUAL_IMAGE_WATERMARK_ID,
        TRUSTMARK_WATERMARK_ID,
        CanaryPhrasePlugin,
        DecodedImageWatermark,
        ImagePerceptualFingerprint,
        ImagePerceptualHash,
        ImagePerceptualMatch,
        ImageSoftBindingVerification,
        ImageWatermark,
        ImageWatermarkDependencyError,
        InvisibleFramePlugin,
        LexicalSubstitutionPlugin,
        SemanticParaphrasePlugin,
        StatisticalSentencePatternPlugin,
        SyntacticVariationPlugin,
        TextWatermarkDetection,
        TextWatermarkEligibility,
        TextWatermarkEmbedding,
        TextWatermarkParameters,
        TextWatermarkPipelineResult,
        TextWatermarkPlugin,
        TextWatermarkQualityReport,
        TextWatermarkRecord,
        TrustMarkBackend,
        TrustMarkLocator,
        WatermarkError,
        apply_text_watermark_plugins,
        assess_text_watermark_eligibility,
        compare_image_perceptual_fingerprints,
        create_image_perceptual_fingerprint,
        decode_image_soft_binding,
        embed_experimental_text_carrier,
        embed_image_soft_binding,
        perceptual_image_watermark_id,
        trustmark_supported_image_mime_types,
        verify_image_soft_binding,
        watermark_id_for_image_soft_binding,
    )
    from pact.web import RateLimitConfig, create_app

_EXPORTS = {
    "CanonicalizationProfile": "pact.canonical",
    "ContentCanonicalizationError": "pact.canonical",
    "canonical_json": "pact.canonical",
    "canonicalize_content": "pact.canonical",
    "PACT_XML_NAMESPACE": "pact.carriers",
    "C2paAsset": "pact.carriers",
    "C2paError": "pact.carriers",
    "C2paReadResult": "pact.carriers",
    "C2paSignerMaterial": "pact.carriers",
    "CarrierError": "pact.carriers",
    "CarrierMode": "pact.carriers",
    "ExternalManifestReference": "pact.carriers",
    "InvisibleLocator": "pact.carriers",
    "StructuredCarrierExtraction": "pact.carriers",
    "TextCarrierExtraction": "pact.carriers",
    "build_c2pa_manifest_definition": "pact.carriers",
    "build_external_manifest_reference": "pact.carriers",
    "c2pa_pdf_embedding_supported": "pact.carriers",
    "c2pa_supported_builder_mime_types": "pact.carriers",
    "c2pa_supported_embedded_document_mime_types": "pact.carriers",
    "c2pa_supported_embedded_image_mime_types": "pact.carriers",
    "c2pa_supported_reader_mime_types": "pact.carriers",
    "embed_c2pa_image": "pact.carriers",
    "embed_c2pa_manifest_in_pdf": "pact.carriers",
    "embed_c2pa_manifest_in_zip_document": "pact.carriers",
    "embed_html_carrier": "pact.carriers",
    "embed_text_carrier": "pact.carriers",
    "embed_xml_carrier": "pact.carriers",
    "extract_c2pa_manifest_from_pdf": "pact.carriers",
    "extract_c2pa_manifest_from_zip_document": "pact.carriers",
    "extract_html_carrier": "pact.carriers",
    "extract_text_carrier": "pact.carriers",
    "extract_xml_carrier": "pact.carriers",
    "pdf_external_manifest_reference": "pact.carriers",
    "read_c2pa_asset": "pact.carriers",
    "sign_c2pa_document": "pact.carriers",
    "sign_c2pa_manifest_store": "pact.carriers",
    "CryptographyError": "pact.crypto",
    "base64url_decode": "pact.crypto",
    "base64url_encode": "pact.crypto",
    "ConfidenceInterval": "pact.detection",
    "EvidenceSignal": "pact.detection",
    "HypothesisTest": "pact.detection",
    "Probe": "pact.detection",
    "ProbeAnalysisReport": "pact.detection",
    "ProbeConclusion": "pact.detection",
    "ProbeEvidencePackage": "pact.detection",
    "ProbeEvidenceSignature": "pact.detection",
    "ProbeKind": "pact.detection",
    "ProbeMeasurement": "pact.detection",
    "ProbeResponse": "pact.detection",
    "ProbeSet": "pact.detection",
    "TrainingUseRiskLevel": "pact.detection",
    "TrainingUseRiskReport": "pact.detection",
    "analyze_probe_responses": "pact.detection",
    "create_probe_set": "pact.detection",
    "create_training_use_risk_report": "pact.detection",
    "responses_from_jsonl": "pact.detection",
    "ClaimantIdentity": "pact.identity",
    "DeviceBindingError": "pact.identity",
    "DeviceIdentityBinding": "pact.identity",
    "EncryptedFileIdentityStore": "pact.identity",
    "IdentityError": "pact.identity",
    "IdentityNotFoundError": "pact.identity",
    "IdentityStorageError": "pact.identity",
    "KeyringIdentityStore": "pact.identity",
    "LocalDeviceBindingStore": "pact.identity",
    "normalize_registry_url": "pact.identity",
    "inspect_content": "pact.inspection",
    "ClaimMeaning": "pact.manifest",
    "C2PAAction": "pact.manifest",
    "C2PAIngredient": "pact.manifest",
    "ContentBinding": "pact.manifest",
    "Manifest": "pact.manifest",
    "ManifestError": "pact.manifest",
    "ManifestSignature": "pact.manifest",
    "SignedManifest": "pact.manifest",
    "VerificationReport": "pact.manifest",
    "sign_manifest": "pact.manifest",
    "verify_manifest": "pact.manifest",
    "Permission": "pact.policy",
    "PermissionValue": "pact.policy",
    "Policy": "pact.policy",
    "PolicyEntry": "pact.policy",
    "PolicyError": "pact.policy",
    "PrivacyAuditError": "pact.privacy",
    "PrivacyAuditReport": "pact.privacy",
    "PrivacyFinding": "pact.privacy",
    "PrivacySeverity": "pact.privacy",
    "audit_public_json_payload": "pact.privacy",
    "audit_registry_claim_payload": "pact.privacy",
    "audit_signed_manifest_publication": "pact.privacy",
    "ChallengePurpose": "pact.registry",
    "ClaimVerificationReport": "pact.registry",
    "ClaimantProfile": "pact.registry",
    "DisputeRecord": "pact.registry",
    "DisputeStatus": "pact.registry",
    "EvidenceProfile": "pact.registry",
    "FileRegistryStore": "pact.registry",
    "KeyRotationRequest": "pact.registry",
    "MutationChallenge": "pact.registry",
    "MutationRequest": "pact.registry",
    "PostgresRegistryStore": "pact.registry",
    "RegisteredClaim": "pact.registry",
    "RegistryBatch": "pact.registry",
    "RegistryCertificateAuthority": "pact.registry",
    "RegistryError": "pact.registry",
    "RegistryEvent": "pact.registry",
    "RegistryEventType": "pact.registry",
    "RegistryService": "pact.registry",
    "RegistryStore": "pact.registry",
    "RegistryStoreError": "pact.registry",
    "SqliteRegistryStore": "pact.registry",
    "TrustLabel": "pact.registry",
    "TrustTier": "pact.registry",
    "VerificationLabel": "pact.registry",
    "merkle_root": "pact.registry",
    "AuthProvider": "pact.server",
    "AwsLambdaRoute": "pact.server",
    "CognitoAuthorizerConfig": "pact.server",
    "DeploymentMode": "pact.server",
    "RouteAuth": "pact.server",
    "RouteConfig": "pact.server",
    "RuntimeConfig": "pact.server",
    "SecurityProfile": "pact.server",
    "StoreBackend": "pact.server",
    "aws_lambda_routes": "pact.server",
    "create_registry_store": "pact.server",
    "default_routes": "pact.server",
    "PERCEPTUAL_IMAGE_WATERMARK_ID": "pact.watermarks",
    "TRUSTMARK_WATERMARK_ID": "pact.watermarks",
    "CanaryPhrasePlugin": "pact.watermarks",
    "DecodedImageWatermark": "pact.watermarks",
    "ImagePerceptualFingerprint": "pact.watermarks",
    "ImagePerceptualHash": "pact.watermarks",
    "ImagePerceptualMatch": "pact.watermarks",
    "ImageSoftBindingVerification": "pact.watermarks",
    "ImageWatermark": "pact.watermarks",
    "ImageWatermarkDependencyError": "pact.watermarks",
    "InvisibleFramePlugin": "pact.watermarks",
    "LexicalSubstitutionPlugin": "pact.watermarks",
    "SemanticParaphrasePlugin": "pact.watermarks",
    "StatisticalSentencePatternPlugin": "pact.watermarks",
    "SyntacticVariationPlugin": "pact.watermarks",
    "TextWatermarkDetection": "pact.watermarks",
    "TextWatermarkEligibility": "pact.watermarks",
    "TextWatermarkEmbedding": "pact.watermarks",
    "TextWatermarkParameters": "pact.watermarks",
    "TextWatermarkPipelineResult": "pact.watermarks",
    "TextWatermarkPlugin": "pact.watermarks",
    "TextWatermarkQualityReport": "pact.watermarks",
    "TextWatermarkRecord": "pact.watermarks",
    "TrustMarkBackend": "pact.watermarks",
    "TrustMarkLocator": "pact.watermarks",
    "WatermarkError": "pact.watermarks",
    "apply_text_watermark_plugins": "pact.watermarks",
    "assess_text_watermark_eligibility": "pact.watermarks",
    "compare_image_perceptual_fingerprints": "pact.watermarks",
    "create_image_perceptual_fingerprint": "pact.watermarks",
    "decode_image_soft_binding": "pact.watermarks",
    "embed_experimental_text_carrier": "pact.watermarks",
    "embed_image_soft_binding": "pact.watermarks",
    "perceptual_image_watermark_id": "pact.watermarks",
    "trustmark_supported_image_mime_types": "pact.watermarks",
    "verify_image_soft_binding": "pact.watermarks",
    "watermark_id_for_image_soft_binding": "pact.watermarks",
}

__all__ = sorted([*_EXPORTS, "__version__"])

__version__ = PACKAGE_VERSION


def __getattr__(name: str) -> object:
    """Load public exports on demand."""

    if name in {"RateLimitConfig", "create_app"}:
        from pact import web

        return getattr(web, name)
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
